import React from 'react'
import { motion } from 'framer-motion'

const Education = () => {
  return (
    <div id='Education' className='relative z-1 top-52 container flex flex-col items-center p-2'>
      <motion.h1 
      whileHover={{textUnderlinePosition:2}}
      className=' text-white text-5xl'>Education And Certifications</motion.h1>
      <p  className='text-white'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque, amet nostrum. Odio reiciendis esse ullam, sequi totam natus, vel, eligendi maxime doloremque quod ut error mollitia quas nisi asperiores ex.
      Earum consectetur neque vel voluptatem, iusto, reiciendis deserunt dolore in assumenda repellendus cupiditate corporis debitis veniam itaque porro, amet sit ratione unde est sint magni sunt? Dolorum debitis eum vel!
      Odio laboriosam aut esse? Aliquid quas optio veritatis quibusdam eum mollitia officiis magni facere. Harum maiores delectus dolor placeat in! Maxime tempora est excepturi dignissimos ipsum, eligendi tempore! Placeat, soluta.
      Consequatur labore excepturi cumque minima fugit consequuntur dolor quod quas quo similique tenetur dolorem est molestias, distinctio laudantium magni eaque eum explicabo natus sint vel iusto. Accusantium vel cupiditate pariatur!
      Nobis sequi unde aliquam quisquam impedit suscipit dolores repudiandae sint non! Sit nemo adipisci architecto odit aliquam sed voluptas aut, earum quo! Eos rem harum hic laboriosam animi, alias in?
      Ut fugit molestiae soluta corrupti a repellendus. Reiciendis dolorum fugit doloribus. Velit enim deleniti, maxime perspiciatis pariatur, dolorum commodi cupiditate veritatis, rem cumque nisi eligendi possimus. Voluptatum rerum assumenda voluptatem.
      Aperiam commodi, id aliquam, accusantium incidunt atque facere, ratione culpa iste voluptas assumenda eligendi nulla itaque! Asperiores repellendus culpa officiis error. Fugiat esse nobis harum est ullam commodi asperiores eum?
      Accusantium mollitia expedita, eum aliquid pariatur hic quo veritatis, reprehenderit nobis ratione porro ullam inventore quas blanditiis culpa magni! Ducimus, excepturi? Eveniet, omnis beatae. Soluta eius explicabo fugiat quod laboriosam.
      Corporis eaque aperiam reprehenderit excepturi possimus fuga ipsum molestiae, similique quisquam quam saepe voluptas quaerat. Sed, quam facere ea corporis molestias soluta praesentium ipsum alias, ullam impedit maiores. Consequuntur, amet?
      Dignissimos, voluptas voluptatum, architecto beatae ab dolorum praesentium fugit odio corporis dolorem placeat reiciendis modi repellendus error porro rerum sint vero vitae delectus iusto nulla amet deleniti veniam. Quaerat, voluptas.
      Quibusdam modi sapiente corrupti quo! Exercitationem aperiam provident nulla dolor ut voluptatem expedita adipisci enim doloribus voluptatibus delectus reprehenderit aut quasi, sequi velit eum ullam consectetur a distinctio fuga temporibus!
      Quo cumque, temporibus soluta eos repellat hic architecto quibusdam quasi numquam consectetur sed totam veritatis animi aliquam beatae iste. Eligendi sapiente ea, fugit dignissimos praesentium nemo neque ipsam a impedit.
      Accusamus non aperiam dolores dignissimos! Facere voluptate cum, explicabo doloribus commodi odio sunt consequatur nisi sapiente vel quis id amet omnis hic obcaecati voluptas tempora? Ipsa dicta a veritatis in.
      Ducimus, blanditiis modi. Itaque quibusdam minima, unde beatae nisi necessitatibus tenetur architecto error, dolores voluptatum laboriosam! Eveniet, quo in facilis molestias pariatur, porro at autem voluptas mollitia itaque officia illum!
      Laborum nihil est ipsum doloremque. Facilis nesciunt cumque facere, dignissimos, fugiat ipsa deleniti commodi eius ducimus error cum? Magni soluta est asperiores voluptate? Error vero optio illum laudantium, quisquam magni.
      Minima, tenetur velit ipsum, vero officia vitae totam saepe dolor ducimus magnam impedit enim non perferendis omnis assumenda molestias mollitia eum sapiente eos! Accusantium illo temporibus eos rerum doloribus animi.
      Nesciunt eum adipisci itaque maxime quas perspiciatis nemo! Esse deleniti illum tempore dolorum voluptatibus alias doloribus saepe dignissimos corrupti nobis magni minus, cupiditate aliquam molestias, ipsam ducimus provident ut totam.
      Quisquam recusandae facilis natus minima eaque esse, consequatur magni maiores perferendis possimus quas ipsam id tempore ipsa maxime ea ducimus libero distinctio qui? Quo officia eos voluptate facilis doloremque maiores!
      Asperiores error, expedita atque at, perspiciatis corporis amet similique nemo officia culpa eos blanditiis ut sapiente tenetur quidem distinctio. Totam, architecto! Iusto, a! Optio commodi fugiat quis ipsam! Nesciunt, deleniti?
      Nesciunt, sunt beatae. Magnam quibusdam suscipit quas saepe quia id ipsa optio, adipisci, dolorum nobis molestiae reiciendis soluta dicta deserunt voluptates recusandae voluptatum quae, ad aliquid repellat sit commodi mollitia!
      Nisi dolore deserunt ex excepturi deleniti alias minima provident fugit quisquam rerum! Doloremque excepturi suscipit illo aliquam quas quia similique, earum, sunt accusamus consequuntur, debitis unde explicabo deleniti iusto a.
      Rerum ipsam quas iusto omnis, corporis deserunt dolorem modi culpa, pariatur ullam, officia beatae? Obcaecati amet ipsam, veniam iste a maiores expedita ea ab similique molestias quo, nobis, ratione eos?
      Voluptates et sint pariatur omnis nostrum exercitationem voluptatum consectetur quisquam doloremque animi libero repellat magni cum ratione enim suscipit totam nulla labore consequuntur ab, hic saepe. Dolores magni architecto accusamus!
      Enim ad architecto, laboriosam aliquid deserunt molestiae maxime corporis mollitia recusandae sit, iure consectetur debitis. Magnam assumenda dolores ipsam reiciendis qui cupiditate. Enim consectetur perspiciatis itaque alias fugiat porro fugit.
      Quasi illum eligendi aliquid sapiente facere blanditiis quisquam possimus repellendus tempora quam. Suscipit aut tenetur id modi! Aliquid ipsam nemo, sapiente atque numquam nihil. Ratione vero ex totam. Odit, iusto.
      Laborum cupiditate iure consectetur, facere ducimus reprehenderit sed vitae error vero mollitia suscipit eaque sit voluptatum. Deleniti vero beatae pariatur cum qui voluptatem minima enim ullam ducimus possimus. Odio, excepturi.
      A accusamus vel eius enim rem pariatur quia aut tempore repellendus distinctio totam assumenda harum autem sapiente magnam quidem veritatis, necessitatibus quod, laboriosam architecto. Odio tempora cumque dolores soluta recusandae.
      Harum laboriosam, nemo veniam consequuntur ducimus necessitatibus sapiente, voluptatem culpa cumque sint at perferendis repudiandae et provident odit rem autem iste sequi? Quos laborum cumque ipsam delectus sunt natus ipsa?
      Aspernatur quam architecto aliquid repellendus animi iste illo praesentium inventore quo qui ipsa, doloribus pariatur? Eum dolores vel commodi natus ipsum, earum illum ab minima voluptatibus, harum illo ipsa amet.
      Inventore culpa molestias aut, explicabo deserunt possimus non sint asperiores similique rerum, dolore nostrum, debitis blanditiis officia. Quo cum quos recusandae velit. Odit, in tenetur perferendis voluptas sit commodi! Facere.
      Quam cupiditate quo quibusdam voluptate quas optio reiciendis suscipit, sed magnam, rerum, quidem eius? Asperiores obcaecati nam rem, deleniti consequuntur quidem qui quibusdam earum voluptas id, aperiam temporibus labore expedita?
      Sunt vitae eveniet nam at nulla autem mollitia accusamus cum vel doloremque similique animi voluptatem odio saepe ex sed possimus pariatur magnam, fuga sit illum! Facere asperiores harum temporibus iure.
      Optio quidem dignissimos labore hic autem dicta, provident ipsa laborum rerum itaque? Incidunt fugiat quaerat hic maiores dolores eligendi nisi, distinctio, nam natus quam tempore eaque, veniam inventore magni quo!
      Necessitatibus aliquam dolore commodi, mollitia reprehenderit consequatur, incidunt earum blanditiis suscipit fuga vero! Suscipit aspernatur dolor nisi similique amet nobis, nemo dolorem aut vitae sequi culpa reprehenderit fugit sit ratione.
      Dolore, numquam! Error quas labore sapiente saepe voluptatum veritatis tenetur velit doloremque cupiditate nisi ex ad delectus sit deserunt necessitatibus voluptate voluptas nam, rem illum nobis quis ipsam exercitationem! Inventore.
      Culpa facere inventore ratione qui eius deserunt dicta facilis illum consectetur, nam, adipisci ab labore perspiciatis odio exercitationem laudantium veniam hic placeat. Ipsam doloribus sapiente eaque officia, magni culpa earum?
      Magni ad dolore officia odio assumenda ex veniam itaque? Doloremque hic sed iusto optio. Voluptatum itaque, officiis, labore doloribus quisquam quidem error voluptatem ipsa quasi fugiat omnis debitis, fugit delectus?
      Ipsam quaerat alias quisquam eaque itaque atque dolor, blanditiis sed molestias veniam qui minus ea reiciendis rerum eos iure dolorem, placeat praesentium aut voluptatibus nesciunt voluptate. Sint officia possimus illum!
      Doloribus quod voluptates praesentium commodi officia fugiat delectus porro at, cupiditate corrupti mollitia officiis sint necessitatibus est expedita vero deleniti minus! Autem ratione, distinctio et iste eligendi nesciunt error? Voluptatibus!
      Quidem cupiditate sunt mollitia quae possimus tempora soluta, laborum debitis doloribus qui voluptatum sint quo vero error hic labore perferendis exercitationem illum adipisci earum iusto facilis. Nihil sed pariatur eum?
      Nemo et ullam maxime incidunt nihil deserunt, quo expedita totam, dolorem possimus itaque obcaecati dolore voluptatum iusto consequuntur cumque asperiores saepe pariatur delectus neque at magni enim sit? Dignissimos, natus?
      Dolore voluptatem ab, repellat atque, architecto veritatis ratione sed pariatur voluptatum nobis possimus aliquid quia doloremque corporis at ipsa voluptatibus natus beatae et provident molestiae quis eum? In, repellat vel!
      Corrupti laborum necessitatibus dicta, dignissimos nemo quam molestiae blanditiis nostrum, sit id distinctio pariatur reiciendis maiores beatae veritatis veniam. Quasi quo voluptatem at tenetur porro temporibus reprehenderit nostrum dicta magnam.
      Officiis impedit magni voluptate vero blanditiis, totam id incidunt voluptatum repellendus! Reprehenderit cumque deserunt accusantium, dignissimos magnam sequi unde rem quisquam ex asperiores numquam voluptas aperiam, accusamus labore molestiae nesciunt!
      Molestias repellendus, voluptas nihil reiciendis repellat mollitia temporibus dolorem earum sint, minus odio dolor vitae. Rerum qui, nesciunt at magnam enim officiis voluptate adipisci iusto, eum totam maxime doloremque suscipit.
      Blanditiis, nobis officiis nostrum placeat accusamus sequi dolorum a quod perspiciatis rerum tempora commodi expedita, in eligendi! Doloremque laudantium, nisi ducimus dicta quam, doloribus architecto quisquam natus distinctio perferendis sapiente.
      Esse, ipsam nostrum sed alias excepturi error accusamus illo magni doloremque vel quas quasi ratione laudantium cum totam impedit aut numquam beatae doloribus asperiores obcaecati est? Inventore vitae sint porro.
      Neque laboriosam dignissimos optio quaerat. Quos non inventore fuga eos perspiciatis eius provident, iusto porro debitis nobis deleniti illum unde. Doloribus facere optio numquam delectus vero voluptatibus rem soluta aut.
      Et nulla aspernatur fuga ex labore, velit libero voluptates dolore, ducimus, cupiditate corporis tenetur odio sed. Quos, aspernatur ut recusandae hic odit distinctio suscipit libero tempore, eveniet maxime voluptas perferendis.
      Incidunt voluptatibus, rerum veniam deleniti dolor quos impedit natus error! Minima necessitatibus, cupiditate voluptas aspernatur quia, non nostrum quas illum debitis quae cumque a. Reiciendis eligendi esse cupiditate at impedit!
      Beatae officiis quod optio dicta impedit enim delectus distinctio reprehenderit excepturi suscipit culpa, rem eius eum perspiciatis totam voluptatem odit, omnis quisquam. Sed, accusamus neque. Deserunt beatae vitae modi excepturi!
      Provident, corporis voluptatum. Rem accusantium, tempore culpa laborum ipsum numquam aliquam fugit nihil veritatis alias dicta perferendis, architecto nisi voluptatibus aspernatur quidem sequi! Sed ipsum voluptates voluptate, nobis molestias alias?
      Voluptatum consequatur eos, vero fugit iusto ducimus qui neque aut cupiditate corporis animi omnis quis debitis labore voluptas nobis. Possimus ad aspernatur amet deleniti dolore quibusdam omnis doloribus aliquam accusantium.
      Molestias aliquam vero laboriosam consequatur voluptatibus beatae magni cupiditate inventore ipsum? Reprehenderit, incidunt. Amet totam cumque quas alias, molestias, consequatur ipsum dolorum quae dignissimos dicta necessitatibus, consectetur perferendis. Incidunt, unde.
      Perferendis tenetur quidem, libero distinctio id blanditiis dolores adipisci quasi eaque accusamus ut fugiat alias at rerum ullam magnam dignissimos. Asperiores, rem! Placeat, id quidem. Earum facilis voluptatibus recusandae eum!
      Voluptatem facere dolorum perferendis nobis facilis magnam ad. Nobis eligendi corporis, sed eveniet inventore repellat necessitatibus perspiciatis recusandae quasi reiciendis nam beatae itaque rerum eius veritatis libero deleniti velit est?
      Tenetur aut eaque magni minus aliquam officia eligendi soluta cum. Alias ex nihil voluptas dignissimos voluptatibus at necessitatibus nostrum nulla reiciendis. Deserunt earum eligendi quas molestiae soluta. Deserunt, itaque cupiditate.
      Quas saepe neque debitis harum laboriosam magnam consequatur ad error fuga doloremque esse eos deserunt dolore porro voluptate, impedit excepturi tenetur, corporis vero labore. Blanditiis excepturi explicabo id expedita? Pariatur.
      Qui sit veniam, dolorem alias excepturi eaque facilis dignissimos vitae fugiat? Necessitatibus magnam, perferendis assumenda libero modi laudantium. Corporis sequi, quod quisquam voluptatem commodi sint temporibus ab ea ullam possimus!
      Aut dolorem temporibus facere beatae, id, ex adipisci porro saepe ratione velit aperiam vel blanditiis in quae. Exercitationem maiores expedita suscipit laudantium, explicabo natus culpa numquam, magnam sunt architecto deleniti?
      Cum dolore et nostrum, aliquid fugiat voluptate possimus porro, dolorum iste sed enim unde vel debitis voluptas molestias, non error veritatis itaque sequi! Magnam fugit cupiditate temporibus rem labore dicta!
      Impedit tempora minima, provident atque, totam tenetur eligendi voluptatem pariatur, quis omnis in quia nostrum? Numquam quasi ea, explicabo id fugit voluptates optio, recusandae quis magnam ipsam dolor asperiores cumque.
      Libero itaque iusto nihil magnam sapiente sit expedita quibusdam optio magni eos impedit dolor, odio aut beatae harum placeat quod, incidunt illo dolorem reiciendis voluptatem perspiciatis velit qui pariatur? Distinctio!
      Nam accusamus consectetur asperiores facere obcaecati, qui incidunt optio itaque deleniti ratione. Iste laboriosam quaerat delectus voluptas, maxime aliquam magni quo reiciendis similique eos illo deleniti eveniet accusantium placeat expedita.
      Eaque facilis velit perspiciatis fugiat similique ut vel est saepe exercitationem, temporibus ipsam reprehenderit odio nisi veritatis vero error facere tempora voluptatem consequuntur magnam eligendi voluptates provident! Explicabo, eligendi architecto.
      Voluptas ducimus qui molestias ex velit veritatis exercitationem quo magni ab explicabo blanditiis expedita dolorum, a molestiae ratione impedit et optio. Eius nesciunt quisquam aliquid facere eum assumenda, modi recusandae!
      Temporibus at enim, fugit reprehenderit recusandae ipsum voluptatibus libero voluptate voluptas iure nulla, facilis, debitis autem cum a ratione! Aspernatur nesciunt odit architecto error accusantium eligendi adipisci nobis impedit voluptate!
      Dolorem voluptatem nesciunt laboriosam quisquam, iste aspernatur nemo rem suscipit eveniet officiis repellat eaque doloremque excepturi tempore cupiditate, quo dolorum ad ipsum. Perspiciatis necessitatibus beatae distinctio architecto quod dolore inventore!
      Rerum deleniti, incidunt minima iusto maxime accusantium cum. Exercitationem labore dignissimos eos animi ut maiores nobis cum inventore, minus illum eligendi voluptatum unde cumque ad soluta, repellat reprehenderit provident error?
      Inventore veniam ipsum optio quam ex! Molestiae, qui omnis at modi asperiores repudiandae minima! Nihil vel fugiat ipsum fugit reprehenderit et commodi aspernatur, dolor mollitia earum expedita, veniam, placeat recusandae?
      Velit, cupiditate nam laborum pariatur optio voluptatum nulla dolorem iste veniam non labore autem dolores cum sunt nostrum est, ullam quaerat facilis? Quisquam in perspiciatis veniam? Alias facilis ex aperiam!
      Ratione eius quisquam labore perferendis asperiores tenetur error optio explicabo placeat, nostrum eum quos debitis enim aspernatur neque, omnis et voluptas. Sint aspernatur omnis necessitatibus voluptatibus aliquam sed ut quae.
      Et excepturi pariatur inventore maxime, distinctio, eveniet numquam ut incidunt aspernatur perspiciatis sapiente molestias blanditiis eum. Unde illum obcaecati dolorem? Quas consequuntur maxime, atque in libero praesentium accusantium repellendus pariatur!
      Laborum doloribus voluptatem, rem aperiam nobis pariatur saepe labore ad, quam minus asperiores animi dolores cum ex, cumque distinctio soluta architecto. Est necessitatibus quisquam id! Earum in dolores voluptatum exercitationem.
      Assumenda nam maxime expedita adipisci, tenetur debitis labore perspiciatis ex deleniti incidunt itaque neque! Perspiciatis rem eos architecto libero qui inventore illo, incidunt reprehenderit eligendi consequuntur delectus tempore ducimus facere.
      Eaque unde accusantium nisi doloremque. Optio tempore harum rerum facilis deserunt fugit accusantium perferendis ut! Minima praesentium corporis corrupti magnam cumque laborum in repellendus soluta, molestias quos, suscipit beatae? Modi.
      Voluptatem, facilis iusto? Quisquam, laboriosam? Illo aperiam alias sit possimus suscipit est dolore ipsam! Ab, cumque debitis optio nemo cum animi? Nulla voluptate, ipsa impedit vitae incidunt et delectus ex?
      Voluptas aliquid et natus, itaque repellat aspernatur dignissimos ea corporis voluptates delectus sapiente mollitia repudiandae? Ducimus, deserunt praesentium aperiam odit doloribus vel! Placeat commodi corporis quos neque amet consequuntur excepturi.
      Ab, dolores! Veniam cumque optio quam, est officia a aut explicabo repudiandae eveniet aliquid alias. Corporis veniam iste adipisci inventore ducimus harum. Placeat, quisquam accusamus. Beatae amet odio harum repudiandae.
      Voluptatibus pariatur ab itaque sunt, labore eius odio iusto incidunt repellat consequuntur nulla deleniti facilis quam provident necessitatibus quo saepe officia suscipit repellendus tempore ex tempora. Eum beatae assumenda magnam.
      Saepe hic rerum ipsa iusto dolore, tenetur quasi quae fugit, officiis officia debitis voluptatum illum minus assumenda in unde sequi perferendis consequatur ad expedita ducimus explicabo quibusdam! Possimus, temporibus provident.
      Mollitia soluta repellendus quibusdam sunt labore expedita impedit earum rem dolorem repudiandae. Vitae aliquid, incidunt dolorum doloribus excepturi similique unde, porro, nobis dolor aut ullam natus magni praesentium deleniti dolore.
      Blanditiis quaerat neque omnis voluptates repellat quidem, eligendi exercitationem alias nam architecto sapiente mollitia reiciendis debitis? Esse non aperiam enim quibusdam eum suscipit vitae ad! Atque est asperiores quidem voluptatibus.
      Reiciendis nihil maxime praesentium ab a, vel, cumque minima illo consequatur molestiae, tenetur libero possimus eligendi earum magni. Aspernatur voluptatibus alias molestias quae sequi earum iste commodi vero a deleniti?
      Tenetur ex dolores quidem est architecto veniam iste labore molestias aspernatur? Officia dignissimos cumque voluptatem commodi, ipsum explicabo saepe placeat vero praesentium libero at recusandae suscipit vitae veritatis culpa perferendis?
      Ipsam, vero odio? Ipsa quos corrupti, modi odio quod qui voluptatem explicabo deleniti minima harum sapiente minus ipsum earum repudiandae possimus debitis sed, nam unde, sunt libero repellendus quae cumque!
      Asperiores consequuntur accusamus quos molestias quia quas nemo sunt maiores ipsam eos iure perspiciatis tempora illo sint dolor officia voluptate architecto, eius aliquam laborum omnis! Obcaecati, dolorem ab. Iste, adipisci!
      Nesciunt, perferendis quod, eos nulla cupiditate libero voluptates id aperiam, similique aut nam quaerat quos ratione expedita eum cumque deleniti soluta. Facilis corporis libero quas non, molestias at repudiandae neque.
      Pariatur at, ducimus illo nam commodi temporibus hic cum qui laboriosam nihil. Veritatis consectetur rem ratione ex maxime adipisci quis, architecto et expedita facere reiciendis eos quam fugiat sit fuga?
      Nulla qui distinctio sit modi obcaecati temporibus! Quia repudiandae expedita eum, est provident eligendi, porro cupiditate officiis dolorum autem reiciendis perspiciatis illo, molestias repellendus assumenda itaque! Quod nobis veritatis alias.
      Ipsa commodi modi esse aliquid earum et dolore quis veniam culpa repellendus ut at explicabo neque, nesciunt, maxime iusto deserunt. Expedita vitae fugit voluptatum corporis saepe neque illum nostrum cupiditate.
      Unde numquam facilis ut rem illo quod optio ullam quos repellat eum perferendis in nobis nesciunt labore consequuntur accusantium doloribus, sapiente voluptatum! Alias, totam autem? Reprehenderit porro aspernatur exercitationem delectus.
      Laborum, molestiae! Nulla in recusandae voluptate reiciendis temporibus minima, alias tempora cumque repudiandae, magnam autem quod ea id vitae distinctio laborum quis odit, doloribus asperiores illum. Ad ut cumque incidunt.
      Voluptas officia natus necessitatibus cupiditate non vitae eveniet veniam dolore quia vel qui praesentium culpa quidem sapiente soluta, consequuntur aspernatur rerum tenetur repellat voluptate nobis rem libero quos! Excepturi, voluptatibus.
      Itaque velit iste vitae nisi iure aliquam obcaecati! Fugit sint magni esse officiis consequuntur reprehenderit, quae cumque, maiores architecto aut quos molestiae deserunt. Error laudantium corporis repellendus dignissimos, nisi dolorem?
      Perferendis saepe ipsum autem quis blanditiis ea. Earum commodi suscipit, sint perferendis debitis qui at eius numquam minus tenetur? Laborum, illum error nemo ullam enim quibusdam. Recusandae sed aliquid minima?
      Esse, eveniet quidem qui molestiae similique porro impedit unde suscipit incidunt tenetur ullam reprehenderit et voluptates, magnam exercitationem delectus nulla vel nam, beatae eum sequi. Aliquid soluta quod ducimus quia!
      Veritatis deleniti dolorum dolore asperiores! Eum molestiae eius excepturi assumenda soluta, nemo eligendi aspernatur? Quisquam, optio. Similique voluptatum nihil, aliquam temporibus tenetur expedita modi aspernatur esse fugiat quod ex amet!
      Incidunt libero porro dolor in officiis! Provident, officia totam atque quibusdam rerum voluptatem tempora non facilis. Nulla aliquam eaque ut labore, cumque ab eveniet et impedit iure deserunt consequuntur unde.
      Soluta hic vitae quaerat, voluptas magni dolorem at mollitia, praesentium quas ea facere illum maxime dolore nulla voluptate fuga ducimus eligendi odio? Ad dolorem laborum vel, fugiat explicabo unde dolorum.</p>
    </div>
  )
}

export default Education